// This file is generated by npm run build:icons

export type IconName =
	| "calendar"
	| "check"
	| "close"
	| "copy"
	| "discord"
	| "discourse"
	| "download"
	| "edit"
	| "eye"
	| "github"
	| "hide"
	| "plus-only"
	| "plus"
	| "show"
	| "trash"
	| "twitter-alt"
	| "twitter"
	| "upload"
	| "youtube";
